/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'postId' : string,
}
export interface Earning {
  'source' : { 'ad' : null } |
    { 'nft' : null } |
    { 'tip' : null },
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface LiveStream {
  'id' : string,
  'title' : string,
  'startedAt' : Time,
  'thumbnailUrl' : string,
  'host' : Principal,
  'description' : string,
  'isActive' : boolean,
  'viewers' : bigint,
}
export interface Message {
  'content' : string,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface NFT {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'isSold' : boolean,
  'imageUrl' : string,
  'price' : bigint,
}
export interface Post {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'author' : Principal,
  'videoUrl' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'createdAt' : Time,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyNFTListing' : ActorMethod<[string], undefined>,
  'createLiveStream' : ActorMethod<[string, string, string, string], undefined>,
  'createNFTListing' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'createPost' : ActorMethod<
    [string, string, string, string, string, bigint, Array<string>],
    undefined
  >,
  'createProfile' : ActorMethod<[string, string, string], undefined>,
  'endLiveStream' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllConversations' : ActorMethod<[], Array<Message>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[string], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getEarningsHistory' : ActorMethod<[Principal], Array<Earning>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getNFTById' : ActorMethod<[string], [] | [NFT]>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getPostLikesCount' : ActorMethod<[string], bigint>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getStreamById' : ActorMethod<[string], [] | [LiveStream]>,
  'getTotalEarnings' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<
    [Principal],
    {
      'followerCount' : bigint,
      'followingCount' : bigint,
      'totalPosts' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinStream' : ActorMethod<[string], undefined>,
  'leaveStream' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'listActiveLiveStreams' : ActorMethod<[], Array<LiveStream>>,
  'listAllNFTListings' : ActorMethod<[], Array<NFT>>,
  'listNFTsByCreator' : ActorMethod<[Principal], Array<NFT>>,
  'markMessagesAsRead' : ActorMethod<[Principal], undefined>,
  'markNFTAsSold' : ActorMethod<[string], undefined>,
  'recordEarning' : ActorMethod<
    [Principal, bigint, { 'ad' : null } | { 'nft' : null } | { 'tip' : null }],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];