/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'videoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Time,
  'avatarUrl' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'postId' : IDL.Text,
});
export const Earning = IDL.Record({
  'source' : IDL.Variant({
    'ad' : IDL.Null,
    'nft' : IDL.Null,
    'tip' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const NFT = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isSold' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const LiveStream = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'startedAt' : Time,
  'thumbnailUrl' : IDL.Text,
  'host' : IDL.Principal,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'viewers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyNFTListing' : IDL.Func([IDL.Text], [], []),
  'createLiveStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createNFTListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'endLiveStream' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllConversations' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getEarningsHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Earning)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getNFTById' : IDL.Func([IDL.Text], [IDL.Opt(NFT)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPostLikesCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getStreamById' : IDL.Func([IDL.Text], [IDL.Opt(LiveStream)], ['query']),
  'getTotalEarnings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'followerCount' : IDL.Nat,
          'followingCount' : IDL.Nat,
          'totalPosts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinStream' : IDL.Func([IDL.Text], [], []),
  'leaveStream' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listActiveLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'listAllNFTListings' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
  'listNFTsByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(NFT)], ['query']),
  'markMessagesAsRead' : IDL.Func([IDL.Principal], [], []),
  'markNFTAsSold' : IDL.Func([IDL.Text], [], []),
  'recordEarning' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        IDL.Variant({ 'ad' : IDL.Null, 'nft' : IDL.Null, 'tip' : IDL.Null }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'videoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Time,
    'avatarUrl' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'postId' : IDL.Text,
  });
  const Earning = IDL.Record({
    'source' : IDL.Variant({
      'ad' : IDL.Null,
      'nft' : IDL.Null,
      'tip' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const NFT = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isSold' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const LiveStream = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'startedAt' : Time,
    'thumbnailUrl' : IDL.Text,
    'host' : IDL.Principal,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'viewers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyNFTListing' : IDL.Func([IDL.Text], [], []),
    'createLiveStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createNFTListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'endLiveStream' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllConversations' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getEarningsHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Earning)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getNFTById' : IDL.Func([IDL.Text], [IDL.Opt(NFT)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPostLikesCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getStreamById' : IDL.Func([IDL.Text], [IDL.Opt(LiveStream)], ['query']),
    'getTotalEarnings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'followerCount' : IDL.Nat,
            'followingCount' : IDL.Nat,
            'totalPosts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinStream' : IDL.Func([IDL.Text], [], []),
    'leaveStream' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listActiveLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'listAllNFTListings' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
    'listNFTsByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(NFT)], ['query']),
    'markMessagesAsRead' : IDL.Func([IDL.Principal], [], []),
    'markNFTAsSold' : IDL.Func([IDL.Text], [], []),
    'recordEarning' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          IDL.Variant({ 'ad' : IDL.Null, 'nft' : IDL.Null, 'tip' : IDL.Null }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };